#ddev-generated
services:
  db:
    ports: []
    networks:
      - ddev_default
    volumes:
      - "./master.cnf:/etc/mysql/conf.d/my.cnf"
    command: --server-id=1 --log-bin=mysql-bin --binlog-format=row
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: replica_user
      MYSQL_PASSWORD: replication_password
  replica_1:
    image: "mysql:8.0"
    container_name: "ddev-${DDEV_SITENAME}-replica-1"
    depends_on:
      - db
    command: --server-id=2 --log-bin=mysql-bin --binlog-format=row
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: replica_user
      MYSQL_PASSWORD: replication_password
    networks:
      - ddev_default
    volumes:
      - "./mysql_replication/alter_replica_user.sql:/docker-entrypoint-initdb.d/1-alter_replica_user.sql"
      - "./mysql_replication/setup_replication.sh:/docker-entrypoint-initdb.d/2-setup_replication.sh"
  replica_2:
    image: "mysql:8.0"
    container_name: "ddev-${DDEV_SITENAME}-replica-2"
    depends_on:
      - db
    command: --server-id=3 --log-bin=mysql-bin --binlog-format=row
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: replica_user
      MYSQL_PASSWORD: replication_password
    networks:
      - ddev_default
