#ddev-generated
services:
  db:
    ports: []
    networks:
      - ddev_default
    command: --server-id=1 --log-bin=mysql-bin --binlog-format=row
  replica_1:
    image: mysql:8.0
    container_name: "ddev-${DDEV_SITENAME}-replica-1"
    depends_on:
      - db
    command: --server-id=2 --log-bin=mysql-bin --binlog-format=row
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: replication_user
      MYSQL_PASSWORD: replication_password
      USER: stijn
    networks:
      - ddev_default
    volumes:
      - "./mysql_replication/master-db.sql:/docker-entrypoint-initdb.d/1-master-db.sql"
      - "./mysql_replication/alter_user_for_replica.sql:/docker-entrypoint-initdb.d/2-alter_user_for_replica.sql"
      - "./mysql_replication/setup_replication.sh:/docker-entrypoint-initdb.d/3-setup_replication.sh"
  replica_2:
    image: mysql:8.0
    container_name: "ddev-${DDEV_SITENAME}-replica-2"
    depends_on:
      - db
    command: --server-id=3 --log-bin=mysql-bin --binlog-format=row
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: replication_user
      MYSQL_PASSWORD: replication_password
    networks:
      - ddev_default
    volumes:
      - "./mysql_replication/alter_user_for_replica.sql:/docker-entrypoint-initdb.d/1-alter_user_for_replica.sql"
      - "./mysql_replication/setup_replication.sh:/docker-entrypoint-initdb.d/2-setup_replication.sh"
